### ISSUE TITLE
Can this works with Kinect V2.0 (the new Kinect that also works with Xbox one)?

### ISSUE THREAD

**Issue by AdiGaash** [jloehr/AR-Sandbox#2]
Hi Jloehr, 
Please let me know...

Adi

**Comment by jloehr** [comment]
Kinect V2 does not work out of the box. But it shouldn't be that much work to get it working.
Replace the Kinect V1 Plugin with the V2 one. Then change https://github.com/jloehr/AR-Sandbox/blob/master/Assets/Script/DepthMesh.cs to retrieve the Depth Image from the new plugin.

**Comment by Rafael1991** [comment]
Hello, we're students and trying something similar.
Could u tell me where exactly  "Then change https://github.com/jloehr/AR-Sandbox/blob/master/Assets/Script/DepthMesh.cs to retrieve the Depth Image from the new plugin."  is this part of code, which I need to change? I don't see it.

Best regards

**Comment by AdiGaash** [comment]
I will check later on, anyways I do have an alternative solution that
really works great for me to gather only the depth image at realtime. I
used a project named "UnityKinectV2DeferredRendering". Its a very basic one
but you should be able to extract efficiently just the depth feed.

Good luck :)

Adi Gaash

**Comment by Rafael1991** [comment]
I got the exact unity Version (5.4.0b17) but can't play your project, I get a warning that it was last opend in a different Version ...tried it more than once..and so i get Compiler Errors.. not sure what's going on :D unity can be a pain in the ass...

**Comment by AdiGaash** [comment]
again, for the specific AR-Sandbox project, I'm not sure I can help you.
Please send the specific compiler error\s in order for me to try to provide
help.

**Comment by Rafael1991** [comment]
solved it for the AR-Sandbox..was using Win 10, but needed win 7 or 8.
But thanks :)

**Comment by jloehr** [comment]
Hi, I am looking into it, upgrading the project to Unity 2019.1.0f2, cleaning couple of things up, fixing related compiler errors and upgrading to Kinect V2 SDK. Though latter one might be more time consuming. 

I may have to remove the AForge Lib in case it is not compatible with the newer Unity version. Copying the DLL into the project is hacky anyway. So if you have any open source Blur/Smoothing lib or implementation, that works in Unity, I'd be glad to use it.

**Comment by jloehr** [comment]
Done, the project is now on Unity 2019.1.0f2 (though can be be backported to earlier version) and I added Kinect V2 support. Kinect V2 is now the default sensor.

For the AForge the System.Drawing.dll still need to be copied. Otherwise there will be errors.

After a quick test it seems the performance isn't that great for larger mesh sizes. Though there is much room for improvement in case it's going to be an issue. Like mentioned by @AdiGaash, a good start would be to just forward the depth image to the GPU and do all the mesh transform, cropping and blur as part of the vertex shader.

I'm going to close this issue as Kinect V2 support has been added.
